name: State repo analyze changes
on:
  workflow_call:

jobs:
  linter-and-validate-release-coherence:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calculate changes
        id: calculate_changes
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - '**.yaml'
              - '**.yml'
              - '!.github/**'
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: |
            const changedFiles = JSON.parse(${{ toJson(steps.calculate_changes.outputs.changed_files) }});

            changedFiles.forEach( f => {
              console.log(f)
            });

            const result = {}

            return result;