name: State repo helm
on:
  workflow_call:
    inputs:
      apply:
        required: true
        type: boolean
      config_file:
        required: false
        type: string
        default: .github/deployments-config.yaml
jobs:
  helm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install js-yaml
      - name: Parse config file
        id: parse_config
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const yaml = require('js-yaml');

            const config = yaml.load(fs.readFileSync("${{ inputs.config_file }}", 'utf8'));

            console.log("hi")
      # - name: Setup / Azure Login
      #   uses: Azure/login@v2
      #   with:
      #     client-id: ${{ env.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ env.AZURE_TENANT_ID }}
      #     subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      # - name: 