name: State repo helm
on:
  workflow_call:
    inputs:
      apply:
        required: true
        type: boolean
      environment:
        required: true
        type: string
      config_file:
        required: false
        type: string
        default: .github/deployments-config.yml
jobs:
  helm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install js-yaml
      - name: Parse config file
        id: parse_config
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const path = require("path");
            const yaml = require('js-yaml');

            const configPath = path.join("${{ github.workspace }}", "${{ inputs.config_file }}");

            console.log(configPath);

            const config = yaml.load(fs.readFileSync(configPath, 'utf8'));

            const { provider } = config;
            
            const { cluster_name, identifier } = config.environments["${{ inputs.environment }}"];

            const result = {
              provider,
              cluster_name,
              identifier,
            }

            switch(provider) {
              case 'azure':
                if([process.env.AZURE_TENANT_ID, process.env.AZURE_SUBSCRIPTION_ID].includes(undefined)) throw new Error(`Unconfigured provider ${provider}`)
              default:
                throw new Error(`Unknown provider: ${provider}`)
            }

            console.log(result);

            return result;

      # - name: Setup / Azure Login
      #   uses: Azure/login@v2
      #   with:
      #     client-id: ${{ env.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ env.AZURE_TENANT_ID }}
      #     subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      # - name: 