name: State repo analyze changes
on:
  workflow_call:

jobs:
  linter-and-validate-release-coherence:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calculate changes
        id: calculate_changes
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            changed:
              - '**.yaml'
              - '**.yml'
              - '!.github/**'
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: |
            const path = require("path");

            const changedFiles = JSON.parse(${{ toJson(steps.calculate_changes.outputs.changed_files) }});
            
            const ignoredDirectories = [".github", ".docs"];
            const ignoredFiles = ["helmfile.yaml"];

            changedFiles.forEach( f => {
  
              console.log(`Processing file: ${f}`)
              const pathComponents = path.normalize(f).split(path.sep)

              if(ignoredDirectories.includes(pathComponents[0])) return;
              if(ignoredFiles.includes(pathComponents.at(-1))) return;

              const [kind, tenant, app, file] =  pathComponents;

              console.log(`Found changed file: ${f}`)

              console.log("kind: " + kind + " tenant " + tenant + " app " + app  + " file " + file)
            });

            const result = {}

            return result;